#!/usr/bin/env bash
set -eu

cd "$(dirname "$0")/.."

echo "==> Removing old public files…"
rm -rf public/*
cp -r assets/* public/
echo "==> Building packages…"
ember build

echo "==> copying builded packages to public…"
cp -r dist/* public/	

